In [615]:
import pandas as pd

In [616]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [617]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [618]:
import numpy as np

Creating arrays

In [619]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Multi-dimensional arrays

In [620]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Randomly generated arrays

In [621]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

Element-wise operations

In [622]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

Comparison operations

In [623]:
a >= 2

array([False, False,  True,  True,  True])

Summarizing operations

In [624]:
a.min()

np.int64(0)

In [625]:
a.sum()

np.int64(10)

Linear Algebra refresher

In [626]:
u =np.array([2,4,5,6])

In [627]:
v = np.array([1,0,0,2])

In [628]:
w =u + v
w

array([3, 4, 5, 8])

In [629]:
x = u.dot(v)
x

np.int64(14)

Identity Matrix

In [630]:
I =np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [631]:
U= [[2,1,0],
   [1,2,1],
   [0,1,2]]

Inverse

In [632]:
U_inv = np.linalg.inv(U)
U_inv

array([[ 0.75, -0.5 ,  0.25],
       [-0.5 ,  1.  , -0.5 ],
       [ 0.25, -0.5 ,  0.75]])

Pandas dataframes manipulation library

Dataframes

In [633]:
import pandas as pd

In [634]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [635]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [636]:
df.head()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [637]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [638]:
df['id'] = [1,2,3,4,5]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [639]:
df['Engine HP'] /100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

Filtering

In [640]:
df[df['Year']>= 2015]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [641]:
df[df['Make'] == 'Nissan']

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

String Operations

In [642]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [643]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ','_').str.lower()
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340,5

Summarizing operations

In [644]:
df.MSRP

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [645]:
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP        id
count     5.000000    4.00000          5.000000      5.000000  5.000000
mean   2010.400000  202.75000          4.400000  30186.000000  3.000000
std      11.260551   51.29896          0.894427  18985.044904  1.581139
min    1991.000000  138.00000          4.000000   2000.000000  1.000000
25%    2010.000000  180.00000          4.000000  27150.000000  2.000000
50%    2017.000000  206.00000          4.000000  32340.000000  3.000000
75%    2017.000000  228.75000          4.000000  34450.000000  4.000000
max    2017.000000  261.00000          6.000000  54990.000000  5.000000

Missing Values

In [646]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
id                   0
dtype: int64

Grouping

In [ ]:
```
SELECT 
transmission_type,
AVG(msrp) as avg_price
FROM cars
GROUP BY transmission_type
```

In [ ]:
df.groupby('Transmission Type')['MSRP'].mean()